### ISSUE TITLE
flutter 3 error

### ISSUE THREAD

**Issue by mahadydev** [yama-yeah/glassmorphism_widgets#3]
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Src/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance?.addPostFrameCallback((_) {}

this issue occurred when upgraded to flutter 3. can you please look into it

**Comment by yama-yeah** [comment]
I am currently busy with my university studies and have not been able to get around to revising the warning statement.
If you are dissatisfied with the current situation, please either wait until I am free or fork this repository and fix it yourself.
Also, I can't tell what is causing the problem by just showing you the warning messages, so please explain how the problem occurred and submit the source code that is causing the problem.
example:
I execute this code. but showed this error.
```
void main() {
  string a=1;
}
```
Error compiling to JavaScript:
Info: Compiling with sound null safety
lib/main.dart:3:3:
Error: 'string' isn't a type.
  string a=1;
  ^^^^^^
Error: Compilation failed.

**Comment by yama-yeah** [comment]
I am currently busy with my university studies and have not been able to get around to revising the warning statement.
If you are dissatisfied with the current situation, please either wait until I am free or fork this repository and fix it yourself.
Also, I can't tell what is causing the problem by just showing you the warning messages, so please explain how the problem occurred and submit the source code that is causing the problem.
example:
I execute this code. but showed this error.
```
void main() {
  string a=1;
}
```
Error compiling to JavaScript:
Info: Compiling with sound null safety
lib/main.dart:3:3:
Error: 'string' isn't a type.
  string a=1;
  ^^^^^^
Error: Compilation failed.

**Comment by yama-yeah** [comment]
This is not my package's bug.
please read this issue.
https://github.com/daohoangson/flutter_widget_from_html/issues/769

**Comment by yama-yeah** [comment]
I released new version.
please upgrade package.
